### ISSUE TITLE
signatures of unknown trust

### ISSUE THREAD

**Issue by ReenigneArcher** [hapakaien/archlinux-package-action#32]
I get the following when running this action now.

```txt
  checking keyring...
  checking package integrity...
  error: glibc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
  :: File /var/cache/pacman/pkg/glibc-2.36-6-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
  error: gcc-libs: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
  Do you want to delete it? [Y/n] 
  :: File /var/cache/pacman/pkg/gcc-libs-12.2.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
  error: binutils: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
  Do you want to delete it? [Y/n] 
  :: File /var/cache/pacman/pkg/binutils-2.39-3-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
  error: gcc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
  Do you want to delete it? [Y/n] 
  :: File /var/cache/pacman/pkg/gcc-12.2.0-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
  error: libtool: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
  error: failed to commit transaction (invalid or corrupted package)
  Do you want to delete it? [Y/n] 
  :: File /var/cache/pacman/pkg/libtool-2.4.7-5-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
  Do you want to delete it? [Y/n] 
  Errors occurred, no packages were upgraded.
```

I have not researched this heavily, but did find this: https://www.reddit.com/r/archlinux/comments/rc1z0f/frederick_schwan_signature_issues

Maybe some clues there on how to solve it.

**Comment by GameTec-live** [comment]
this issue is still happening, making this action sadly unusable, because it doesnt generate the srcinfo without downloading all of the dependencys

**Comment by ReenigneArcher** [comment]
@GameTec-live this fork has my fix in it. https://github.com/toitlang/archlinux-package-action

This action doesn't seem to be maintained though so you might want to find an alternative. I ended up deleting my fork as I didn't want to maintain it... ended up just building in docker directly.

**Comment by GameTec-live** [comment]
> @GameTec-live this fork has my fix in it. https://github.com/toitlang/archlinux-package-action
> 
> This action doesn't seem to be maintained though so you might want to find an alternative. I ended up deleting my fork as I didn't want to maintain it... ended up just building in docker directly.

sad that theres basically no way of running the makepkg commands in docker... i now just used sed and manipulated the files directly...
